### ISSUE TITLE
Unhandled Exception: System.Exception - Error Reading P3SASetup.cs during Patch Application

### ISSUE THREAD

**Issue by eduardgasparyan** [clempo2/P3EmptyGame#2]
When applying the patch to the P3SampleApp, an unhandled exception occurred. The exception message is as follows:

`Unhandled Exception: System.Exception: Unexpected EOF (End of File) while reading P3SampleApp\Assets\Scripts\GUI\P3SASetup.cs.`

The patch application process was unable to complete successfully due to this error.

P3 SDK version - V0.8

P3EmptyGame version - V0.8.2

**Comment by clempo2** [comment]
Please attach your copy of P3SASetup.cs
This has to be the exact file that P3Patch was reading.
Are you running on Windows?

**Comment by eduardgasparyan** [comment]
Sure. P3SampleProject is not modified and downloaded from the multimorphic webpage. 
I'm running on Windows 11 VM. 
[P3SASetup.cs.zip](https://github.com/clempo2/P3EmptyGame/files/11754478/P3SASetup.cs.zip)

**Comment by eduardgasparyan** [comment]
Also tried with Windows 10 and got same result.

**Comment by clempo2** [comment]
P3EmptyGame_V0.8.2 is corrupt because it was created against a modified P3SampleApp
This issue is fixed in P3EmptyGame_V0.8.3

**Comment by clempo2** [comment]
P3EmptyGame_V0.8.2 is corrupt because it was created against a modified P3SampleApp
This issue is fixed in P3EmptyGame_V0.8.3
